/*
 * Programmed by: Michael Ian A. Santiago
 * Course/yr: BCS22
 * 
 */
package fightingGame;

public class Control extends javax.swing.JFrame {

    private Panel panel;
    private Menu m;
    
    public Control(Panel panel , Menu m) {
        this.panel = panel;
        this.m = m;
        initComponents();
        setSize(480, 300);
        setLocationRelativeTo(null);
        setTitle("Controls");
    }
    
    public Control(){ }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        controls = new javax.swing.JLabel();
        player1 = new javax.swing.JLabel();
        player2 = new javax.swing.JLabel();
        control1 = new javax.swing.JLabel();
        control2 = new javax.swing.JLabel();
        control3 = new javax.swing.JLabel();
        control4 = new javax.swing.JLabel();
        control5 = new javax.swing.JLabel();
        control6 = new javax.swing.JLabel();
        control7 = new javax.swing.JLabel();
        control8 = new javax.swing.JLabel();
        control9 = new javax.swing.JLabel();
        control10 = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        controls.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        controls.setForeground(new java.awt.Color(255, 255, 255));
        controls.setText("CONTROLS:");
        getContentPane().add(controls);
        controls.setBounds(190, 30, 130, 40);

        player1.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        player1.setForeground(new java.awt.Color(255, 255, 255));
        player1.setText("PLAYER 1");
        getContentPane().add(player1);
        player1.setBounds(70, 70, 100, 40);

        player2.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        player2.setForeground(new java.awt.Color(255, 255, 255));
        player2.setText("PLAYER 2");
        getContentPane().add(player2);
        player2.setBounds(340, 70, 100, 40);

        control1.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        control1.setForeground(new java.awt.Color(255, 255, 255));
        control1.setText("A - left");
        getContentPane().add(control1);
        control1.setBounds(80, 100, 100, 40);

        control2.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        control2.setForeground(new java.awt.Color(255, 255, 255));
        control2.setText("D - right");
        getContentPane().add(control2);
        control2.setBounds(80, 130, 100, 40);

        control3.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        control3.setForeground(new java.awt.Color(255, 255, 255));
        control3.setText("Q - attack 1");
        getContentPane().add(control3);
        control3.setBounds(80, 160, 100, 40);

        control4.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        control4.setForeground(new java.awt.Color(255, 255, 255));
        control4.setText("W - attack 2");
        getContentPane().add(control4);
        control4.setBounds(80, 190, 100, 40);

        control5.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        control5.setForeground(new java.awt.Color(255, 255, 255));
        control5.setText("E - attack 3");
        getContentPane().add(control5);
        control5.setBounds(80, 220, 100, 40);

        control6.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        control6.setForeground(new java.awt.Color(255, 255, 255));
        control6.setText("ARROW LEFT - left");
        getContentPane().add(control6);
        control6.setBounds(320, 100, 130, 40);

        control7.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        control7.setForeground(new java.awt.Color(255, 255, 255));
        control7.setText("ARROW RIGHT - right");
        getContentPane().add(control7);
        control7.setBounds(310, 130, 130, 40);

        control8.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        control8.setForeground(new java.awt.Color(255, 255, 255));
        control8.setText("1 - attack 1");
        getContentPane().add(control8);
        control8.setBounds(340, 160, 100, 40);

        control9.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        control9.setForeground(new java.awt.Color(255, 255, 255));
        control9.setText("2 - attack 2");
        getContentPane().add(control9);
        control9.setBounds(340, 190, 100, 40);

        control10.setFont(new java.awt.Font("Maiandra GD", 0, 12)); // NOI18N
        control10.setForeground(new java.awt.Color(255, 255, 255));
        control10.setText("3 - attack 3");
        getContentPane().add(control10);
        control10.setBounds(340, 220, 100, 40);

        lblBack.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        lblBack.setForeground(new java.awt.Color(255, 255, 255));
        lblBack.setText("<< Back to Main Menu");
        lblBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        getContentPane().add(lblBack);
        lblBack.setBounds(10, 270, 140, 30);

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 10, 20, 20);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fightingGame/res/optionbg.jpg"))); // NOI18N
        bg.setText("jLabel1");
        bg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(bg);
        bg.setBounds(0, 0, 480, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        setVisible(false);
        this.dispose();
        panel.add(new Menu(panel)); 
        panel.setVisible(true);
        panel.getAudioManager().playClick();
    }//GEN-LAST:event_lblBackMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        setVisible(false);
        this.dispose();
        panel.add(new Menu(panel)); 
        panel.setVisible(true);
        panel.getAudioManager().playClick();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Control().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel control1;
    private javax.swing.JLabel control10;
    private javax.swing.JLabel control2;
    private javax.swing.JLabel control3;
    private javax.swing.JLabel control4;
    private javax.swing.JLabel control5;
    private javax.swing.JLabel control6;
    private javax.swing.JLabel control7;
    private javax.swing.JLabel control8;
    private javax.swing.JLabel control9;
    private javax.swing.JLabel controls;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel player1;
    private javax.swing.JLabel player2;
    // End of variables declaration//GEN-END:variables
}
